### ISSUE TITLE
3dstool fails to work with openssl 1.1.0g

### ISSUE THREAD

**Issue by CaptV0rt3x** [dnasdw/3dstool#13]
Hello guys,

I am on ubuntu 18.04 and i wanted to use 3dstool to test some citra-emu code. However, it doesn't seem to work for me. It fails with the following error.
```/home/jenkins/local/Citra-Sys-Arch/shared_font/3dstool/src/3dscrypt.cpp: In function ‘void FEncryptAesCtrCopyFile(FILE*, FILE*, const CBigNum&, const CBigNum&, n64, n64)’:
/home/jenkins/local/Citra-Sys-Arch/shared_font/3dstool/src/3dscrypt.cpp:22:3: error: ‘AES_ctr128_encrypt’ was not declared in this scope
   AES_ctr128_encrypt(pInBuffer, pOutBuffer, static_cast<size_t>(nSize), &key, uCounter, uEcountBuf, &uNum);
   ^~~~~~~~~~~~~~~~~~
/home/jenkins/local/Citra-Sys-Arch/shared_font/3dstool/src/3dscrypt.cpp:22:3: note: suggested alternative: ‘AES_cfb128_encrypt’
   AES_ctr128_encrypt(pInBuffer, pOutBuffer, static_cast<size_t>(nSize), &key, uCounter, uEcountBuf, &uNum);
   ^~~~~~~~~~~~~~~~~~
   AES_cfb128_encrypt
```

Any solutions ?
